import pandas as pd
from prophet import Prophet
import os

def train_forecast_model(df, store_name, days_ahead=30):
    """
    Train a time-series forecasting model for a specific store using Prophet.
    """
    # Prophet requires specific column names: 'ds' (Date) and 'y' (Target value)
    store_data = df[df['Store'] == store_name].rename(columns={'Date': 'ds', 'Sales': 'y'})
    
    # Initialize and train the Prophet model
    # daily_seasonality=True helps capture daily patterns automatically
    model = Prophet(daily_seasonality=True)
    model.fit(store_data)
    
    # Create a dataframe to hold future dates for prediction
    future = model.make_future_dataframe(periods=days_ahead)
    forecast = model.predict(future)
    
    # Extract predictions for the next 'days_ahead' days
    # 'yhat' is the predicted value
    next_30_days = forecast.tail(days_ahead)[['ds', 'yhat']].copy()
    next_30_days['Store'] = store_name
    next_30_days.rename(columns={'ds': 'Date', 'yhat': 'Predicted_Demand'}, inplace=True)
    
    return next_30_days

# Main execution block
if __name__ == "__main__":
    # Load historical sales data generated by data_gen.py
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)
    data_dir = os.path.join(project_root, 'data')
    
    input_path = os.path.join(data_dir, 'sales_history.csv')
    
    if not os.path.exists(input_path):
        print(f"Error: {input_path} not found. Please run data_gen.py first.")
        exit()

    df = pd.read_csv(input_path)
    
    all_forecasts = []
    unique_stores = df['Store'].unique()
    
    print("Training forecast models for each store...")
    
    # Loop through each store to train individual models
    for store in unique_stores:
        fc = train_forecast_model(df, store)
        all_forecasts.append(fc)
        
    # Combine forecasts from all stores into a single DataFrame
    final_forecast = pd.concat(all_forecasts)
    
    # Round predicted demand to nearest integer (can't sell 0.5 units)
    final_forecast['Predicted_Demand'] = final_forecast['Predicted_Demand'].round().astype(int)
    
    # Save results
    output_path = os.path.join(data_dir, 'forecast_results.csv')
    final_forecast.to_csv(output_path, index=False)
    
    print(f"Forecasting completed: {output_path}")
    print(final_forecast.head())